"""Added pdf

Revision ID: 0292db700fae
Revises: 63751bf2ca5b
Create Date: 2024-07-26 13:12:58.578654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0292db700fae'
down_revision = '63751bf2ca5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf', sa.String(length=256), nullable=False))
        batch_op.alter_column('publication_proof',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('utilization_proof',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('utilization_proof',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
        batch_op.alter_column('publication_proof',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
        batch_op.drop_column('pdf')

    # ### end Alembic commands ###
