"""Initial migration

Revision ID: 39297d18cb08
Revises: 
Create Date: 2024-07-16 10:43:17.284077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39297d18cb08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('editor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('abstract', sa.String(length=512), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('date_published', sa.Date(), nullable=False),
    sa.Column('publication_name', sa.String(length=128), nullable=False),
    sa.Column('publisher', sa.String(length=64), nullable=False),
    sa.Column('publisher_type', sa.String(length=32), nullable=False),
    sa.Column('publisher_location', sa.String(length=16), nullable=False),
    sa.Column('vol_issue_no', sa.Integer(), nullable=False),
    sa.Column('doi_url', sa.String(length=256), nullable=False),
    sa.Column('isbn_issn', sa.String(length=4), nullable=False),
    sa.Column('web_of_science', sa.Boolean(), nullable=False),
    sa.Column('elsevier_scopus', sa.Boolean(), nullable=False),
    sa.Column('elsevier_sciencedirect', sa.Boolean(), nullable=False),
    sa.Column('pubmed_medline', sa.Boolean(), nullable=False),
    sa.Column('ched_recognized', sa.Boolean(), nullable=False),
    sa.Column('other_database', sa.String(length=128), nullable=False),
    sa.Column('publication_proof', sa.String(length=32), nullable=False),
    sa.Column('citations', sa.Integer(), nullable=False),
    sa.Column('utilization_proof', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi_url')
    )
    op.create_table('author_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('editor_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('editor_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['editor_id'], ['editor.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('editor_project')
    op.drop_table('author_project')
    op.drop_table('project')
    op.drop_table('user')
    op.drop_table('editor')
    op.drop_table('author')
    # ### end Alembic commands ###
